// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bezxwkugbwrwknhnrcsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlenh3a3VnYndyd2tuaG5yY3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTU3NjMsImV4cCI6MjA1ODkzMTc2M30.TRnJV6brY5h4_9HgFfip0xZUeYTR2GnVqMwOBmKHeRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);